#! /bin/sh
# /etc/init.d/rPIserver
#
### BEGIN INIT INFO
# Provides:          WSGI API services
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: WSGI API services
# Description:       Added 5  Nov 2016
### END INIT INFO
# Some things that run always
touch /var/lock/rPIserver

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script"
    cd /home/pi/rPIserver
    /usr/bin/python /home/pi/rPIserver/rPIserver.pyc &
    ;;
  stop)
    echo "Stopping script"
    pkill -9 -f rPIserver
    exit 0
    ;;
  start)
    rPIserver stop
    sleep 5
    rPIserver start
    ;;
  *)
    echo "Usage: /etc/init.d/rPIserver {start|stop}"
    exit 1
    ;;
esac

exit 0
